[server]
headless = true
port = 8501
enableCORS = false

[browser]
serverAddress = ""

[runner]
magicEnabled = false

[scheduler]
userCaching = true

[client]
showErrorDetails = false

[theme]
base = "light"
primaryColor = "#ff4b4b"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#31333f"
font = "sans serif"
